server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: beyza
    password: beyza
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

# openapi configs
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

